// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gujoqycumjxzvachqfgg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd1am9xeWN1bWp4enZhY2hxZmdnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4OTI5OTIsImV4cCI6MjA2NTQ2ODk5Mn0.3yMH1qXMlQ9tSnujfVuGicCYkgpqb8aOwoEeXWaKHCs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);